AWSTemplateFormatVersion: 2010-09-09
# -------------------------------------
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Parameters:
          - vSys2Name
          - vVpc2CIDR
# -------------------------------------
Parameters:
  # --
  vSys2Name:
    Type: String
    Default: shub-alertnat
  vVpc2CIDR:
    Type: String
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3}).(\\d{1,3})/(\\d{1,2})"
    Default: 192.168.1.0/24
# -------------------------------------
# ===========================================================================
# VPC vpc2
# ===========================================================================
Resources:
  VPC2forLambdaNAT:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref vVpc2CIDR
      EnableDnsSupport: true
      EnableDnsHostnames: false
      Tags:
        - Key: Name
          Value: !Sub "${vSys2Name}-vpc"
# -----------------------------------------------
Outputs:
  VPC2forLambdaNATID:
    Description: VPC 2 ID
    Value: !Ref VPC2forLambdaNAT
    Export:
      Name: VPC2forLambdaNATID
